### ISSUE TITLE
[R-Forge #5828] plot2_xts chart.lines function: reverse line order

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xtsExtra#1]
Submitted by: Peter Carl
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=5828&group_id=118&atid=516)

To plot the lines in reverse order, the chart.lines function should read as: 
chart.lines <- function(x, type='l', colorset=1:10, up.col=NULL, dn.col=NULL){
  if(is.null(up.col)) up.col <- 'green'
  if(is.null(dn.col)) dn.col <- 'red'
  if(type == 'h'){
    colors <- ifelse(x[,1] < 0, dn.col, up.col)
    lines(NROW(x):1,x[,1],lwd=2,col=colors,lend=1,lty=1,type='h')
  } else {
    for(i in NCOL(x):1){
      lines(NROW(x):1,x[,i],lwd=2,col=colorset[i],lend=1,lty=1,type='l')
    }
  }
}

The NROW(x):1 order means that the lines will be printed columnwise from left to right (arguably most interesting to least interesting) such that the left-most column will appear on top of the other lines.  That's been a successful strategy for chart.TimeSeries, and it seems to work here as well.

Attached graph is from:

> pccTheme<-xtsExtraTheme()
> pccTheme$col$colorset = rich10equal
> plot2_xts(R, theme=pccTheme)

pcc

Followups:

Date: 2014-08-23 15:00
Sender: Ross Bennett
Marking this as closed per Peter's comment and fix in commit r825.

Date: 2014-08-14 16:02
Sender: Peter Carl
Looks good, this can be closed... pcc

Date: 2014-07-31 21:43
Sender: Ross Bennett
The NROW(x):1 plots the time series backwards. I made the chang to use NCOL(x):1 in the for loop in commit r825

Date: 2014-07-31 02:20
Sender: Peter Carl
A better example:

> pccTheme$col$colorset = redfocus
> plot2_xts(R, theme=pccTheme)

**Comment by rossb34** [comment]
fixed in commit r825
