### ISSUE TITLE
[R-Forge #5874] plot2.xts - error when specifying a function

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xtsExtra#10]
Submitted by: Peter Carl
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=5874&group_id=118&atid=516)

Occurs in line 226:

> plot2_xts(Ad(JNK), FUN=SMA, theme=pccTheme, n=200)
> Error in plot2_xts(Ad(JNK), FUN = SMA, theme = pccTheme, n = 200) : 
>   could not find function 'modify.args'

I'm not sure where that function lives, but it wasn't anywhere obvious to me...

pcc

Followups:

Date: 2014-08-23 16:20
Sender: Ross Bennett
The issue here was how I was matching arguments for FUN. I was only matching arguments passed in through dots (...) and expecting the function to have an 'R' argument for the data. I now also check for an 'x' argument. I will make it clear in the documentation that we will specifically check for and efficiently handle the arguments named 'R' or 'x' in FUN that expect the data. 

see fix in commit r833

Date: 2014-08-14 21:27
Sender: Peter Carl
Here's a different error, in the same situation:

> plot2_xts(R, FUN='SMA', n=10)
> FUN function failed with message Error in inherits(x, 'xts') : argument 'x' is missing, with no default

No traceback.

Date: 2014-08-14 21:16
Sender: Peter Carl
oops, found it in xtsExtra namespace.

**Comment by rossb34** [comment]
this has been fixed
