### ISSUE TITLE
[R-Forge #5876] plot2.xts - error: no transformation when multi.panel=#

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xtsExtra#12]
Submitted by: Peter Carl
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=5876&group_id=118&atid=516)

When setting multi.panel equal to a number to specify the number of panels per device, the function isn't used to transform the data.  The correct number of panels is drawn across devices, however.
# works

> plot2_xts(R, FUN='CumReturns', geometric=FALSE, multi.panel=TRUE, theme=pccTheme)
> # doesn't transform the data
> 
> plot2_xts(R, FUN='CumReturns', geometric=FALSE, multi.panel=2, theme=pccTheme)

See attached pdf.

Followups:

Date: 2014-08-23 15:42
Sender: Ross Bennett
see fix in commit r832

**Comment by rossb34** [comment]
fixed in commit r832
