### ISSUE TITLE
[R-Forge #5890] plot2.xts - phantom axis labels

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xtsExtra#13]
Submitted by: Peter Carl
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=5890&group_id=118&atid=516)

When I do:

plot2_xts(R, multi.panel=TRUE, yaxis.same=FALSE)

I get the attached graph.  Note the numbers floating in the top of the frame, and the overlap in labels on the second chart.  I don't get those artifacts when I run:

plot2_xts(R, multi.panel=TRUE, yaxis.same=TRUE)

Followups:

Date: 2014-08-31 18:26
Sender: Peter Carl
Looks good, thanks.

Date: 2014-08-30 15:45
Sender: Ross Bennett
fixed in commit r837

**Comment by rossb34** [comment]
fixed in commit r837
