### ISSUE TITLE
[R-Forge #5892] plot2.xts - add stacked bar chart.type

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xtsExtra#14]
Submitted by: Peter Carl
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=5892&group_id=118&atid=516)

I see that replacing chart.lines within the function with the following:

``` r
chart.bars <- function(x, colorset=1:10, ...){
    positives = negatives = x
    for(column in 1:NCOL(x)){
        for(row in 1:NROW(x)){ 
            positives[row,column]=max(0,x[row,column])
            negatives[row,column]=min(0,x[row,column])
        }
    }
    barplot(t(positives), add=TRUE, col=colorset, axisnames = FALSE, axes = FALSE, ...)
    barplot(t(negatives), add=TRUE , col=colorset, axisnames = FALSE, axes = FALSE, ...)
}
```

...gets really close as a way to do stacked/unstacked bar charts.  Still needs some parameterization to get the geometry correct.

**Comment by rossb34** [comment]
This should be an enhancement, not a bug

**Comment by joshuaulrich** [comment]
Issue moved to xts, since this `plot.xts` code now resides there.
