### ISSUE TITLE
[R-Forge #5894] plot2.xts - xaxis incomplete

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xtsExtra#15]
Submitted by: Peter Carl
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=5894&group_id=118&atid=516)

With the modification to remove coarse.time, the xaxis no longer draws to the end of the data like it used to.  In the attached, note that the data continues past the end of the xaxis.  I think that there was some code that deliberately drew the axis from the start of the data to the end; it probably needs to be restored.

Followups:

Date: 2014-08-31 23:22
Sender: Ross Bennett
This was caused by using axTicksByTime to draw the x-axis range and grid lines. axTicksByTime only goes to an index value of 150 whereas axTicksByTime2 goes to an index value of 152 which is the number of observations of the data.

> data(edhec)
> R <- edhec[,1:4]
> tail(axTicksByTime2(R),2)
> 2009 2009 
>  145  152 
> tail(axTicksByTime(R),2)
> \nJan\n2009 \nJun\n2009 
>         145         150 
> nrow(R)
> [1] 152
> nrow(R)
> [1] 152

I was not able to view the attachment, but I reproduced the bug I think you are referring to.

Date: 2014-08-31 18:23
Sender: Peter Carl
Also, as long as we are using whitespace between panels, there should probably be some between the xaxis and the bottom-most panel.  Changing mgp=c(3,1.5,0) to mgp=c(3,1.5,0.5) gives a small break that seems to work.

**Comment by rossb34** [comment]
This was fixed by using axTicksByTime2 when porting from xtsExtra to xts
