### ISSUE TITLE
[R-Forge #5929] plot2.xts - addSeries doesn't take a color

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xtsExtra#16]
Submitted by: Peter Carl
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=5929&group_id=118&atid=516)

It seems really natural to do the following:

> plot(edhec[,1], colorset=redfocus)
> addSeries(edhec[,3], colorset='blue', on=1)

but addSeries doesn't pick up the color parameter.

If it isn't provided, should it cycle through to the next color in the colorset?  Just an idea - but I'm not sure it's a good one...

pcc

**Comment by rossb34** [comment]
this has been fixed
