### ISSUE TITLE
[R-Forge #5866] plot2.xts - allow rotation of xaxis labels

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xtsExtra#17]
Submitted by: Peter Carl
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=5866&group_id=118&atid=516)

In axTicksByTime, line 304 shows hard-coded parameter for 'las=1', which prevents rotation of xaxis labels.  That should be parameterized so that other label formats or tighter grouping of labels can be done - perhaps via a slot in Theme?

pcc

Followups:

Date: 2014-08-14 19:42
Sender: Peter Carl
We should also allow y axis labels to rotate.

**Comment by rossb34** [comment]
This has been fixed
