### ISSUE TITLE
[R-Forge #5868] plot2.xts - bar chart type

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xtsExtra#4]
Submitted by: Peter Carl
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=5868&group_id=118&atid=516)

Although line type='h' gives a vertical line that can pass as a bar when there's enough data, sometimes you need a barplot() style rectangle instead.

The closest example is chart.StackedBar in PerformanceAnalytics.  It uses barplot() internally, and aligns that plot with axTicksByTime().

I'm not exactly sure how the behavior should work - it might need to act almost exactly like chart.StackedBar.xts if there are multiple columns passed into a single plot (and positive and negative values need to be plotted separately).  If each line gets it's own panel, it's much simpler.

pcc

Followups:

Date: 2014-08-14 20:44
Sender: Peter Carl
This might be a more generally useful comment, but I've had good luck using pretty() with barplot(), specifically for the y-axis.

For example:

``` r
    bp <- barplot(momentum, las=1, horiz=TRUE, axes=FALSE, 
        names.arg=names.arg, xlim = range(pretty(momentum)), ...=...)
    axis(1, at=pretty(momentum))
```

...gives a much better result than without it, keeping the data from being compressed to the edge of the plot area.  

That might be true for lines as well.

**Comment by rossb34** [comment]
this should be an enhancement, not a bug

**Comment by joshuaulrich** [comment]
Issue moved to xts, since this `plot.xts` code now resides there.
