### ISSUE TITLE
[R-Forge #5870] plot2.xts - pass line attributes into chart.lines

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/xtsExtra#6]
Submitted by: Peter Carl
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=5870&group_id=118&atid=516)

Line attributes for lwd, lend, lty and others should be parameterized.  They are currently hard-coded.

Followups:

Date: 2014-08-23 21:36
Sender: Ross Bennett
added attributes to chart.lines in r829 and changed function arguments to be more 'plot-like' in r828.

**Comment by rossb34** [comment]
fixed in commit r828 and r829
